model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    ckpt_path: "/camin1/chlee/latent-diffusion-keratopathy/models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt"
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "jpg"
    cond_stage_key: "txt"
    image_size: 32
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 10000 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
#        image_size: 32
#        in_channels: 8
#        out_channels: 4
#        model_channels: 224
#        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
#        - 8
#        - 4
#        - 2
#        num_res_blocks: 2
#        channel_mult:
#        - 1
#        - 2
#        - 3
#        - 4
#        num_head_channels: 32
              
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
#        ckpt_path: "/camin1/chlee/latent-diffusion-keratopathy/logs/L_slit_beam/ver1/epoch=99.ckpt"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4,4]  # num_down = len(ch_mult)-1  #
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
       
data:
  target: main.DataModuleFromConfig
  params:
#    batch_size: 12
#    num_workers: 0
#    wrap: false
    batch_size: 8
    num_workers: 8
    train:
      target: ldm.data.L_slit_to_beam.BeamOnlyTrain
      params:
        size: 256
        beam_images_list_file: "/camin1/chlee/latent-diffusion-keratopathy/data/L_slit_beam_train_index.txt"
        caption: "slit-beam"
    validation:
      target: ldm.data.L_slit_to_beam.BeamOnlyVal
      params:
        size: 256
        beam_images_list_file: "/camin1/chlee/latent-diffusion-keratopathy/data/L_slit_beam_val_index.txt"
        caption: "slit-beam"
    test:
      target: ldm.data.L_slit_to_beam.BeamOnlyTest
      params:
        size: 256
        beam_images_list_file: "/camin1/chlee/latent-diffusion-keratopathy/data/L_slit_beam_test_index.txt"
        caption: "slit-beam"


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 200
        max_images: 8
        increase_log_steps: True
        
  logger:
    target: pytorch_lightning.loggers.TensorBoardLogger
    params:
      save_dir: logs/ldm_L_slit
      name: ldm_L_slit
      version: ver1
      
  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: logs/ldm_L_slit/ver1
      filename: "{epoch:02d}"
      save_last: True
      save_top_k: -1
      mode: min
      every_n_epochs: 10

trainer:
  benchmark: True
  max_epochs: 202
  precision: 16
